#!/bin/bash
# 🚀 NORTHBAYSTUDIOS.IO DEPLOYMENT SCRIPT
# Generated by THOR-AI Deployment Agent

echo "🚀 THOR-AI Deployment Starting..."
echo "🌐 Setting up Northbaystudios.io"

# Update system
echo "📦 Updating system packages..."
apt update && apt upgrade -y

# Install required packages
echo "🐍 Installing Python and web server..."
apt install -y python3 python3-pip nginx ufw

# Install Flask
echo "⚡ Installing Flask..."
pip3 install flask

# Create web directory
echo "📁 Creating web directory..."
mkdir -p /var/www/northbaystudios
cd /var/www/northbaystudios

# Create the website file
echo "📄 Creating website..."
cat > app.py << 'EOF'
#!/usr/bin/env python3
from flask import Flask

app = Flask(__name__)

@app.route('/')
def home():
    return '''
<!DOCTYPE html>
<html>
<head>
    <title>Northbay Studios - Gaming OS Development</title>
    <style>
        body { 
            background: linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 100%);
            color: #e5e5e5; 
            font-family: monospace; 
            text-align: center; 
            padding: 50px; 
        }
        .logo { 
            font-size: 3rem; 
            color: #00ff88; 
            margin-bottom: 20px; 
        }
        .status { 
            background: rgba(0,255,136,0.1); 
            padding: 20px; 
            border-radius: 10px; 
            margin: 20px auto; 
            max-width: 600px; 
        }
    </style>
</head>
<body>
    <div class="logo">🎮 NORTHBAY STUDIOS</div>
    <div class="status">
        <h2>🚀 LIVE & READY!</h2>
        <p>Custom Gaming OS Development</p>
        <p>YOOPER Kernel • TRINITY AI • VOIP SMS</p>
        <p>✅ Server Online • ✅ DNS Configured • ✅ Business Ready</p>
    </div>
    <p>© 2025 Northbay Studios - Gaming the Future</p>
</body>
</html>
    '''

@app.route('/health')
def health():
    return {'status': 'healthy', 'service': 'northbaystudios'}

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=80)
EOF

# Make executable
chmod +x app.py

# Configure nginx
echo "🌐 Configuring nginx..."
cat > /etc/nginx/sites-available/northbaystudios << 'EOF'
server {
    listen 80;
    server_name northbaystudios.io www.northbaystudios.io 207.246.95.179;
    
    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
EOF

# Enable site
ln -sf /etc/nginx/sites-available/northbaystudios /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Configure firewall
echo "🔥 Configuring firewall..."
ufw allow ssh
ufw allow 80
ufw allow 443
ufw --force enable

# Create systemd service
echo "⚙️ Creating systemd service..."
cat > /etc/systemd/system/northbaystudios.service << 'EOF'
[Unit]
Description=Northbay Studios Website
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/var/www/northbaystudios
ExecStart=/usr/bin/python3 app.py
Restart=always

[Install]
WantedBy=multi-user.target
EOF

# Start services
echo "🚀 Starting services..."
systemctl daemon-reload
systemctl enable northbaystudios
systemctl start northbaystudios
systemctl restart nginx

echo "✅ DEPLOYMENT COMPLETE!"
echo "🌐 Northbaystudios.io is now LIVE!"
echo "🎮 THOR-AI Mission Accomplished!"
